"use client";

import { useEffect, useRef, useState } from "react";
import { ClipboardCheck, Sparkles, Clock, ArrowRight, ArrowLeft, Trophy, CheckCircle2, XCircle } from "lucide-react";
import Link from "next/link";
import { useQuizContext } from "@/contexts/QuizContext";
import axios from "axios";
import toast from "react-hot-toast";
import { useRouter } from "next/navigation";
import { setTimeout } from "timers/promises";

export default function Page() {
  // Modal state for starting the quiz
  const [quizStarted, setQuizStarted] = useState(false);
  
  // Quiz Simulation States
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [selectedOption, setSelectedOption] = useState<number | null>(null);
  const [isAnswerSubmitted, setIsAnswerSubmitted] = useState(false);
  const [score, setScore] = useState(0);
  const [quizCompleted, setQuizCompleted] = useState(false);
  
  // const {currentQuiz} = useQuizContext()
  const {currentQuiz} = useQuizContext()

  const [timer, setTimer] = useState(currentQuiz.timer)
  const intervalIdRef = useRef(null)

  const router = useRouter()

  // Sample mockup questions generated by AI based on user parameters
  const questions = currentQuiz?.quiz || []

  const handleOptionSelect = (index: number) => {
    if (isAnswerSubmitted) return;
    setSelectedOption(index);
    clearInterval(intervalIdRef.current)
  };

  useEffect(() => {
  clearInterval(intervalIdRef.current);  

  if (timer > 0 && quizStarted && !selectedOption) {
    intervalIdRef.current = setInterval(() => {
      setTimer(prevTimer => {
        console.log("timer: ", prevTimer, "selected option index: ", selectedOption);
        
        if (prevTimer <= 1 && !selectedOption) {
          clearInterval(intervalIdRef.current);
          toast.error("times up");
          setIsAnswerSubmitted(true);
          updateSelectOption()
          return 0;
        }
        
        if (prevTimer <= 1) {
          clearInterval(intervalIdRef.current);
          return 0;
        }

        return prevTimer - 1;
      });
    }, 1000);
  }

  return () => clearInterval(intervalIdRef.current);
}, [quizStarted, currentQuestionIndex]);

  async function rotateTokensForSelectOption() {
        try {
            const response = await axios.post(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/v1/auth/rotate-tokens`, {}, {
                withCredentials: true
            })
    
            if (response.data.success) {
              await updateSelectOption()
            }
        } catch (error) {
            console.log(error.response.data.reason || error.message)
            toast.error("Please Login")
            router.push("/login")
        }
    }

  async function updateSelectOption() {
    try {
      await axios.patch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/v1/quiz/update/${currentQuiz._id}`, {questionIndex: currentQuestionIndex, userSelected: questions[currentQuestionIndex].options[selectedOption]}, {withCredentials: true})
    } catch(error) {
      if (error.response.data.reason == "Invalid access token" || error.response.data.reason == "access token is required" || error.response.data.message == "Invalid access token" || error.response.data.message == "access token is required") {
          await rotateTokensForSelectOption()
      }
    }
  }

  const handleConfirmAnswer = () => {
    if (selectedOption === null) return;
    setIsAnswerSubmitted(true);
    updateSelectOption()
    
    if (selectedOption == questions[currentQuestionIndex].options.indexOf(questions[currentQuestionIndex].correctAnswer)) {
      setScore((prev) => prev + 1);
    }
  };

  const handleNextQuestion = () => {
    setSelectedOption(null);
    setIsAnswerSubmitted(false);

    if (currentQuestionIndex + 1 < questions.length) {
      setTimer(currentQuiz.timer)
      setCurrentQuestionIndex((prev) => prev + 1);
    } else {
      setQuizCompleted(true);
    }
  };

  useEffect(() => {
    async function rotateTokens() {
        try {
            const response = await axios.post(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/v1/auth/rotate-tokens`, {}, {
                withCredentials: true
            })
    
            if (response.data.success) {
              await updateQuiz()
            }
        } catch (error) {
            console.log(error.response.data.reason || error.message)
            toast.error("Please Login")
            router.push("/login")
        }
    }

    async function updateQuiz() {
      try {
        await axios.patch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/v1/quiz/update/${currentQuiz._id}`, {score, accuracy: Math.round((score / questions.length) * 100), completed: quizCompleted}, {withCredentials: true})
      } catch(error) {
        if (error.response.data.reason == "Invalid access token" || error.response.data.reason == "access token is required" || error.response.data.message == "Invalid access token" || error.response.data.message == "access token is required") {
          await rotateTokens()
        }
      }
    }

    updateQuiz()
  }, [quizCompleted])

  return (
    <main className="h-dvh w-full bg-zinc-950 text-zinc-50 flex flex-col justify-between p-4 overflow-hidden selection:bg-violet-500/30 selection:text-violet-200 relative">
      
      {/* Absolute Header Navigation */}
      <div className="absolute top-4 left-6 right-6 max-w-2xl mx-auto flex items-center justify-between z-20">
        <Link href="/dashboard" className="flex items-center gap-1.5 text-zinc-400 hover:text-zinc-50 transition-colors text-xs font-medium">
          <ArrowLeft size={14} />
          <span>Exit Quiz</span>
        </Link>
        <div className="flex items-center gap-2">
          <ClipboardCheck size={18} className="text-violet-500" />
          <span className="font-bold tracking-tight text-xs">Prompt<span className="text-violet-500">Quiz</span></span>
        </div>
      </div>

      {/* --- PRE-QUIZ START MODAL (Shown before user clicks Start) --- */}
      {!quizStarted && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-fadeIn">
          <div className="bg-zinc-900 border border-zinc-800 p-6 rounded-2xl w-full max-w-md shadow-2xl relative flex flex-col items-center text-center gap-4">
            
            <div className="absolute top-0 right-0 w-32 h-32 bg-violet-600/10 rounded-full blur-2xl pointer-events-none" />

            <div className="p-3 rounded-2xl bg-zinc-950 border border-zinc-800 text-violet-500 shadow-inner">
              <Sparkles size={28} />
            </div>

            <div className="space-y-1">
              <h2 className="text-xl font-bold tracking-tight">Your AI Quiz is Ready!</h2>
              <p className="text-xs text-zinc-400">
                Topic: <span className="text-zinc-200 font-medium">Advanced JavaScript & React Mechanics</span>
              </p>
            </div>

            {/* Quiz Info Badges */}
            <div className="grid grid-cols-3 gap-2 w-full my-2">
              <div className="p-2.5 rounded-xl bg-zinc-950 border border-zinc-800 text-center">
                <span className="text-[10px] uppercase text-zinc-500 block font-semibold">Questions</span>
                <span className="text-sm font-bold text-zinc-200">{currentQuiz.length} Items</span>
              </div>
              <div className="p-2.5 rounded-xl bg-zinc-950 border border-zinc-800 text-center">
                <span className="text-[10px] uppercase text-zinc-500 block font-semibold">Difficulty</span>
                <span className="text-sm font-bold text-violet-400">{currentQuiz.difficulty}</span>
              </div>
              <div className="p-2.5 rounded-xl bg-zinc-950 border border-zinc-800 text-center">
                <span className="text-[10px] uppercase text-zinc-500 block font-semibold">Timer</span>
                <span className="text-sm font-bold text-zinc-200">{currentQuiz.timer}s / Q</span>
              </div>
            </div>

            <button 
              onClick={() => setQuizStarted(true)}
              className="w-full py-3 bg-violet-600 hover:bg-violet-700 text-white font-medium text-sm transition-all rounded-xl shadow-lg shadow-violet-950 flex items-center justify-center gap-2 cursor-pointer active:scale-98 mt-2"
            >
              <Sparkles size={16} />
              <span>Start Quiz Now</span>
            </button>

          </div>
        </div>
      )}

      {/* --- ACTIVE QUIZ SECTION --- */}
      <section className="flex flex-col bg-zinc-900 border border-zinc-800 p-6 rounded-2xl w-full max-w-xl shadow-2xl relative overflow-hidden my-auto mx-auto">
        
        {/* Subtle background glow */}
        <div className="absolute top-0 right-0 w-40 h-40 bg-violet-600/10 rounded-full blur-3xl pointer-events-none" />

        {!quizCompleted ? (
          <>
            {/* Quiz Header & Progress */}
            <div className="flex items-center justify-between pb-3 mb-4 border-b border-zinc-800 relative z-10">
              <span className="text-xs font-semibold uppercase tracking-wider text-violet-400">
                Question {currentQuestionIndex + 1} of {questions.length}
              </span>
              <div className="flex items-center gap-1.5 text-xs text-zinc-400 bg-zinc-950 px-2.5 py-1 rounded-lg border border-zinc-800">
                <Clock size={13} className="text-violet-400" />
                <span>{timer}s</span>
              </div>
            </div>

            {/* Question Card */}
            <div className="space-y-4 relative z-10">
              <h3 className="text-base font-semibold text-zinc-100">
                {questions[currentQuestionIndex].question}
              </h3>

              {/* Options List */}
              <div className="space-y-2.5">
                {questions[currentQuestionIndex].options.map((option, idx) => {
                  let optionStyles = "bg-zinc-800 border-zinc-700 hover:border-zinc-500 text-zinc-200";
                  
                  if (selectedOption === idx) {
                    optionStyles = "bg-violet-600/20 border-violet-500 text-violet-200";
                  }

                  if (isAnswerSubmitted) {
                    if (option === questions[currentQuestionIndex].correctAnswer) {
                      optionStyles = "bg-emerald-500/20 border-emerald-500 text-emerald-200";
                    } else if (selectedOption === idx && option !== questions[currentQuestionIndex].correctAnswer) {
                      optionStyles = "bg-red-500/20 border-red-500 text-red-200";
                    }
                  }

                  return (
                    <button
                      key={idx}
                      onClick={() => handleOptionSelect(idx)}
                      disabled={isAnswerSubmitted}
                      className={`w-full text-left p-3 rounded-xl border text-xs sm:text-sm font-medium transition-all flex items-center justify-between cursor-pointer ${optionStyles}`}
                    >
                      <span>{option}</span>
                      {isAnswerSubmitted && option === questions[currentQuestionIndex].correctAnswer && (
                        <CheckCircle2 size={16} className="text-emerald-400 shrink-0" />
                       )}
                      {isAnswerSubmitted && selectedOption === idx && option !== questions[currentQuestionIndex].correctAnswer && (
                        <XCircle size={16} className="text-red-400 shrink-0" />
                      )}
                    </button>
                  );
                })}
              </div>

              {/* Action Button */}
              {!isAnswerSubmitted ? (
                <button
                  onClick={handleConfirmAnswer}
                  disabled={selectedOption === null}
                  className={`w-full py-2.5 rounded-xl text-xs sm:text-sm font-medium transition-all flex items-center justify-center gap-2 mt-2 ${
                    selectedOption === null 
                      ? "bg-zinc-800 text-zinc-500 cursor-not-allowed border border-zinc-700" 
                      : "bg-violet-600 hover:bg-violet-700 text-white cursor-pointer shadow-lg shadow-violet-950"
                  }`}
                >
                  <span>Submit Answer</span>
                </button>
              ) : (
                <button
                  onClick={handleNextQuestion}
                  className="w-full py-2.5 bg-violet-600 hover:bg-violet-700 text-white font-medium text-xs sm:text-sm transition-all rounded-xl shadow-lg shadow-violet-950 flex items-center justify-center gap-2 cursor-pointer mt-2"
                >
                  <span>{currentQuestionIndex + 1 < questions.length ? "Next Question" : "View Results"}</span>
                  <ArrowRight size={16} />
                </button>
              )}

            </div>
          </>
        ) : (
          /* --- QUIZ RESULT SCREEN --- */
          <div className="flex flex-col items-center text-center gap-4 py-4 relative z-10">
            <div className="p-3 rounded-2xl bg-zinc-950 border border-zinc-800 text-violet-400 shadow-inner">
              <Trophy size={32} />
            </div>

            <div className="space-y-1">
              <h2 className="text-xl font-bold tracking-tight">Quiz Completed! 🎉</h2>
              <p className="text-xs text-zinc-400">Here is how you performed on this challenge.</p>
            </div>

            <div className="p-4 rounded-xl bg-zinc-950 border border-zinc-800 w-full flex items-center justify-around my-2">
              <div>
                <span className="text-[10px] uppercase text-zinc-500 block font-semibold">Total Score</span>
                <span className="text-lg font-extrabold text-violet-400">{score} / {questions.length}</span>
              </div>
              <div className="h-8 w-[1px] bg-zinc-800" />
              <div>
                <span className="text-[10px] uppercase text-zinc-500 block font-semibold">Accuracy</span>
                <span className="text-lg font-extrabold text-emerald-400">{Math.round((score / questions.length) * 100)}%</span>
              </div>
            </div>

            <div className="flex gap-2 w-full mt-2">
              <Link 
                href="/create-quiz"
                className="flex-1 py-2.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 font-medium text-xs rounded-xl transition-all text-center flex items-center justify-center gap-1.5"
              >
                Create New Quiz
              </Link>
              <Link 
                href="/dashboard"
                className="flex-1 py-2.5 bg-violet-600 hover:bg-violet-700 text-white font-medium text-xs rounded-xl transition-all text-center flex items-center justify-center gap-1.5 shadow-lg shadow-violet-950"
              >
                Dashboard
              </Link>
            </div>
          </div>
        )}

      </section>

      {/* Footer spacer */}
      <div className="text-center text-[10px] text-zinc-500 shrink-0">
        PromptQuiz • AI Learning Engine
      </div>

    </main>
  );
}